"""v1

Revision ID: 79641a3286c2
Revises: 
Create Date: 2025-03-15 17:55:10.341149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79641a3286c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_notes_title'), ['title'], unique=False)

    op.create_table('note_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['public.notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('note_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_note_histories_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_note_histories_id'))

    op.drop_table('note_histories', schema='public')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_notes_title'))
        batch_op.drop_index(batch_op.f('ix_public_notes_id'))

    op.drop_table('notes', schema='public')
    # ### end Alembic commands ###
