"""v2

Revision ID: 3effa2b5ec19
Revises: 13cc4e07b838
Create Date: 2025-03-15 17:20:19.102927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3effa2b5ec19'
down_revision: Union[str, None] = '13cc4e07b838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['public.notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('note_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_note_histories_id'), ['id'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_notes_id')
        batch_op.drop_index('ix_notes_title')
        batch_op.create_index(batch_op.f('ix_public_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_notes_title'), ['title'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_public_notes_title'))
        batch_op.drop_index(batch_op.f('ix_public_notes_id'))
        batch_op.create_index('ix_notes_title', ['title'], unique=False)
        batch_op.create_index('ix_notes_id', ['id'], unique=False)
        batch_op.drop_column('version')

    with op.batch_alter_table('note_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_note_histories_id'))

    op.drop_table('note_histories', schema='public')
    # ### end Alembic commands ###
